[phases.setup]
nixPkgs = [
  "pkgs.python311",
  "pkgs.ffmpeg",
  "pkgs.mesa",
  "pkgs.stdenv.cc",
  "pkgs.libGL",
  "pkgs.glib",
  "pkgs.xorg.libSM",  # Correção aqui
  "pkgs.xorg.libXext" # Correção aqui
]
